// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Loader: typeof import('./src/components/threejs/loader/loader.vue')['default']
    Music: typeof import('./src/components/relax/music.vue')['default']
    Particle: typeof import('./src/components/common/particle.vue')['default']
    PerspectiveCamera: typeof import('./src/components/threejs/camera/perspectiveCamera.vue')['default']
    Raycast: typeof import('./src/components/threejs/raycast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Threejs: typeof import('./src/components/threejs/index.vue')['default']
    ThreeNav: typeof import('./src/components/threejs/threeNav.vue')['default']
    Turntable: typeof import('./src/components/home/turntable.vue')['default']
    Weather: typeof import('./src/components/relax/weather.vue')['default']
  }
}
