module.exports = [
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,270001,1',
        modifyTime: '2023-08-15 15:20:13',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '体力药剂*1',
        id: 108,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTMyTSAJGV-AAA1P6XNnaM402.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '체력 물약*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_1',
        rewardContent: '체력 물약*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Not_Fixed","threshold":35,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,270015,1',
        modifyTime: '2023-08-15 15:20:24',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '隐秘面具*1',
        id: 109,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTMyUWAR24WAAAkwagMnYs140.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '5성 은밀가면*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_2',
        rewardContent: '5성 은밀가면*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Not_Fixed","threshold":35,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,253104,1',
        modifyTime: '2023-08-15 15:20:33',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '镀银宝图*1',
        id: 110,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTMyVCAaphUAAA4vfa_aSA172.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '은 보물 지도*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_3',
        rewardContent: '은 보물 지도*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Not_Fixed","threshold":35,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,279015,1',
        modifyTime: '2023-08-15 15:20:44',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '5星魔偶自选A*1',
        id: 111,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTM18KAQ29MAAA-VNzQ68E957.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '5성 수확 선물함*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_4',
        rewardContent: '5성 수확 선물함*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Once","threshold":5,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,279025,1',
        modifyTime: '2023-08-15 15:22:59',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '5星魔偶自选B*1',
        id: 112,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTM18-AcSYmAABAgG3-OYc499.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '5성 기도 선물함*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_5',
        rewardContent: '5성 기도 선물함*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Once","threshold":5,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,279035,1',
        modifyTime: '2023-08-15 15:31:02',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '5星魔偶自选C*1',
        id: 113,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTM19aAXEx8AAA_aYOCz5E111.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '5성 수호 선물함*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_6',
        rewardContent: '5성 수호 선물함*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Once","threshold":5,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,251004,1',
        modifyTime: '2023-08-15 15:21:50',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '堕落伯爵*1',
        id: 114,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTM1-GAeYqQAAA_6A1Zui4515.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '통용-타락한 백작*1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_7',
        rewardContent: '통용-타락한 백작*1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Once","threshold":2,"rewardCondition":""}',
    },
    {
        remarkDescription: '',
        orderno: 0,
        isBigPrize: '否',
        rewardTitle: '그림 맞추기 게임 성공 보상',
        num: '',
        pid: 92,
        remark: '',
        childs: [],
        activityCode: 'cocmwOneYear',
        rewardId: '1,196276,1',
        modifyTime: '2023-08-15 15:21:59',
        isGlobalLimitedTimes: null,
        defaultDBId: '',
        commentDescription: '横扫千军自选 *1',
        id: 115,
        sonType: '抽奖后发奖',
        isLimited: '否',
        startedTime: null,
        probability: '',
        parentType: '抽奖列表',
        picture:
            'https://image-download.vsplay.com/activity01/M00/17/05/CgEPemTM1_OAf79eAABeiEw-EoA141.png',
        deleted: '0',
        modifyPeople: '',
        isGlobalLimitedDescription: null,
        name: '파죽지세 선택 *1',
        isGlobalLimited: '否',
        gameCode: 'cocmw',
        rewardCode: 'reward_8',
        rewardContent: '파죽지세 선택 *1',
        comment: '',
        endTime: null,
        rewardCondition:
            '{"rewardFrequency":"Once","threshold":1,"rewardCondition":""}',
    },
]
